
# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
development:
  SECRET_KEY: 'sk_test_6KnAKROCnayIRPJ81atmfrDa'
  PUBLISHABLE_KEY: 'pk_test_gdwHN8Hd9MehosmQnDtBJCOi'


AWS_ACCESS_KEY: "AKIAJAEQ2ERFVQTSHJRA"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "buybuyb"
AWS_REGION: "us-east-1"

